### ISSUE TITLE
Consider opened window to not block the shell

### ISSUE THREAD

**Issue by bergmeister** [lzybkr/ShowPSAst#4]
I started using `ShowPSAst` more often recently to help me with writing more 'intelligent' PSScriptAnalyzer rules (and mainly because I cannot think in ASTs yet).
A common scenario is to show and compare multiple scriptblocks side by side where I play around and modify the scriptblock but still want to compare the results to previous ones.

Therefore it would be useful to not block the shell when opening the external window.

**Comment by lzybkr** [comment]
That's a good idea, probably not hard to implement with a background runspace or (slower but even easier to implement) `Start-Job`.

**Comment by mrboring** [comment]
I've started looking into this. Initially I'm trying to use `Start-Job`. I've gotten it working, I even have the job automatically remove itself when `Show-Ast` closes. However, a passed in scriptblock is converted to a string. So I lose the `Ast.Extent` which contains: `File`, `StartLineNumber`, `EndLineNumber`, `StartOffset` and `EndOffset`. This means I can't display the originating file details. I believe this is due to serialization of the `ArgumentList` parameter.

~~Any suggestions on a way around this?~~

I've got a workaround. Rather than passing the AST I pass the values: `File`, `Text`, `StartLineNumber`, `EndLineNumber` and `StartOffset`.  This works.

**Comment by mrboring** [comment]
This has been implemented.

**Comment by lzybkr** [comment]
Closed via https://github.com/lzybkr/ShowPSAst/pull/7

**Comment by bergmeister** [comment]
Awesome. Can we get a new version published or do you want to let it go through some more manual testing first?
